### PR TITLE
Initial E2E system tests (`set_code, authorize_upgrade`)

### LINKED ISSUE #456: Write initial E2E tests for runtime upgrade process
Child issue of #298 .

@karolk91 helpfully looked into #298, and the original scope was too 
Concretely, testing the entire runtime upgrade flow will not work with ad-hoc measures like reusing the chain's current WASM:

> Particularly set_code stuff is problematic:
>
>    For successful path, it requires WASM with increased `specVersion`, otherwise the process fails with an error about "not increased `specVersion`"
>    Considered approaches:
>    a) build some minimal WASM not really related to the real network WASM with some maximum values for `specVersion` and other metadata so it will always be possible to update to this runtime
>    b) get current WASM from `:CODE` storage and increase the `specVersion` by modifying the blob
>    c) run the test conditionally if there is some `env` variable (per chain) that actually provides the wasm to be used for next upgrade (eg, CI Action in fellowship repo that run PETs who also provides locally build WASMs)
>

This issue tracks the smaller subset of tests that **is** possible by reusing current WASM, for example:
1. using `system::set_code` with the same WASM and checking it fails
2. using `set_code_without_checks` with the same WASM, and verifying it succeeds
3. authorizing upgrades (with or without checks) and then running them

Testing the entire upgrade flow end-to-end, with properly constructed new runtimes, can be left for the future, in particular for the PET CI workflow in github.com/polkadot-fellows/runtimes.

### PR DESCRIPTION
**Pull request by karolk91**
Relates to: https://github.com/open-web3-stack/polkadot-ecosystem-tests/issues/298

Will close #456 .

This initial implementation provides 

Scenarios for Polkadot and Kusama relays. These scenearios utilize local pallet Scheduler to execute upgrade related calls as Root:
- call `set_code` with currently used WASM expecting error to happen (this path is checking eg `specVersion` from WASM and will not allow upgrade to pass if it hasn't been incremented)
- call `set_code_without_checks` with currently used WASM expecting success, basically upgrading to the same wasm but version checks are skipped on runtime level thus allowing to pass
- two step approach to upgrade -> `authorize_upgrade` + `apply_authorized_upgrade` with currently used WASM expecting error to happen
- two step approach to upgrade -> `authorize_upgrade_without_checks` + `apply_authorized_upgrade` with currently used WASM expecting success
- check that subsequent `authorize_upgrade` and `authorize_upgrade_without_checks` can override authorized hash

Scenarios for Polkadot/Kusama system chains (AH, BH, People, Coretime, Collectives, Encointer). These scenarios utilize Relay chain's pallet Scheduler to send XCM Transact go gain root on destination chain:
- two step approach to upgrade -> `authorize_upgrade` + `apply_authorized_upgrade` with currently used WASM expecting error to happen
- two step approach to upgrade -> `authorize_upgrade_without_checks` + `apply_authorized_upgrade` with currently used WASM expecting success
- check that subsequent `authorize_upgrade` and `authorize_upgrade_without_checks` can override authorized hash

### CODE REVIEW

File: packages/shared/src/system.ts [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+
+  await client.dev.newBlock({ count: 1 })
+  assertExpectedEvents(await client.api.query.system.events(), [
+    {
+      type: client.api.events.system.UpgradeAuthorized,
+      args: { codeHash: currentWasmHash },
+    },
+  ])
+
+  const authroizedUpgrade = (await client.api.query.system.authorizedUpgrade()).value
```
Comment (rockbmb) [inline packages/shared/src/system.ts:45]:
```suggestion
  const authorizedUpgrade = (await client.api.query.system.authorizedUpgrade()).value
```

File: packages/shared/src/system.ts [hunk 2]
```diff
@@ -0,0 +1,250 @@
...
+
+    await client.dev.newBlock({ count: 1 })
+    assertExpectedEvents(await client.api.query.system.events(), [
+      {
+        type: client.api.events.system.UpgradeAuthorized,
+        args: { codeHash: someHash },
+      },
+    ])
+
+    const authroizedUpgrade = (await client.api.query.system.authorizedUpgrade()).value
```
Comment (rockbmb) [inline packages/shared/src/system.ts:74]:
```suggestion
    const authorizedUpgrade = (await client.api.query.system.authorizedUpgrade()).value
```

File: packages/shared/src/system.ts [hunk 3]
```diff
@@ -0,0 +1,250 @@
...
+import { expect } from 'vitest'
+
+import { assertExpectedEvents, scheduleInlineCallWithOrigin, scheduleLookupCallWithOrigin } from './helpers/index.js'
+import type { RootTestTree } from './types.js'
+
+type SetCodeFn = (code: Uint8Array | HexString) => SubmittableExtrinsic<'promise'>
+type AuthorizeUpgradeFn = (codeHash: string | Uint8Array<ArrayBufferLike>) => SubmittableExtrinsic<'promise'>
+type ExpectedEvents = Parameters<typeof assertExpectedEvents>[1]
+
+async function runAuthorizeUpgradeScenario(
```
[the remark this answers is not in the document]
Comment (karolk91) [reply packages/shared/src/system.ts:41]: @rockbmb , of course, added new part of tests (for system chains) and also introduced some docs in https://github.com/open-web3-stack/polkadot-ecosystem-tests/pull/411/commits/df85f3d06b2c09186e45404d4e07cecb8ec01d58

File: packages/polkadot/src/bridgeHubPolkadot.system.e2e.test.ts [hunk 4]
```diff
@@ -0,0 +1,10 @@
+import { bridgeHubPolkadot, polkadot } from '@e2e-test/networks/chains'
+import { type RelayTestConfig, registerTestTree, systemE2ETestsViaRelay } from '@e2e-test/shared'
+
+const testConfig: RelayTestConfig = {
+  testSuiteName: 'Polkadot Collectives System',
```
[the remark this answers is not in the document]
Comment (karolk91) [reply packages/polkadot/src/bridgeHubPolkadot.system.e2e.test.ts]: You probably reviewed older commit as this has been fixed already

File: packages/shared/src/helpers/index.ts [hunk 5]
```diff
@@ -440,3 +443,109 @@ export interface ParaTestConfig {
  * Union type for all test configurations, whether relay or parachain.
  */
 export type TestConfig = RelayTestConfig | ParaTestConfig
+
+type ArgMatcher = unknown | ((actual: unknown) => boolean)
+
+type EventMatchCriteria<T extends AnyTuple = AnyTuple, N = unknown> = {
```
[the remark this answers is not in the document]
Comment (karolk91) [reply packages/shared/src/helpers/index.ts:509]: Some docs added in: https://github.com/open-web3-stack/polkadot-ecosystem-tests/pull/411/commits/950bc134ee49e9d749d6b1202502b639162272b4

File: packages/shared/src/system.ts [hunk 6]
```diff
@@ -0,0 +1,569 @@
...
+} from './helpers/index.js'
+import type { RootTestTree } from './types.js'
+
+type SetCodeFn = (code: Uint8Array | HexString) => SubmittableExtrinsic<'promise'>
+type AuthorizeUpgradeFn = (codeHash: string | Uint8Array<ArrayBufferLike>) => SubmittableExtrinsic<'promise'>
+type ExpectedEvents = Parameters<typeof assertExpectedEvents>[1]
+
+/**
+ * Runs the authorize upgrade + apply authrozied upgrade scenario
+ * Scenario will fetch WASM from :code storage thus effectively trying to upgrade to the same WASM as currently used
```
[the remark this answers is not in the document]
Comment (karolk91) [reply packages/shared/src/system.ts:30]: Improved docs in https://github.com/open-web3-stack/polkadot-ecosystem-tests/pull/411/commits/950bc134ee49e9d749d6b1202502b639162272b4

File: packages/shared/src/system.ts [hunk 7]
```diff
@@ -0,0 +1,613 @@
...
+ */
+export async function authorizeUpgradeTests<
+  TCustom extends Record<string, unknown> | undefined,
+  TInitStoragesRelay extends Record<string, Record<string, any>> | undefined,
+>(chain: Chain<TCustom, TInitStoragesRelay>) {
+  const [client] = await setupNetworks(chain)
+  return runAuthorizeUpgradeScenario(client, {
+    call: client.api.tx.system.authorizeUpgrade,
+    expectedAfterApply: (hash) => [
+      { type: client.api.events.system.RejectedInvalidAuthorizedUpgrade, args: { codeHash: hash } },
```
Comment (rockbmb) [inline packages/shared/src/system.ts]: If it's not too much work, could you also check the `error` field of `RejectedInvalidAuthorizedUpgrade`?

A runtime upgrade to the same WASM failing is expected, but the reasons for the failure should be (and stay) the same.

File: packages/shared/src/system.ts [hunk 8]
```diff
@@ -0,0 +1,613 @@
...
+ */
+async function runAuthorizeUpgradeAllowToOverrideScenario(
+  client: Client,
+  params: {
+    call: AuthorizeUpgradeFn
+  },
+) {
+  const authorizeHash = async (someHash) => {
+    const call = params.call(someHash).method
+    await scheduleInlineCallWithOrigin(client, call.toHex(), { system: 'Root' })
```
Comment (rockbmb) [inline packages/shared/src/system.ts]: Every instance of `scheduleInlineCallWithOrigin` needs to be given a block provider, which the test config type has: 

https://github.com/open-web3-stack/polkadot-ecosystem-tests/blob/ae7271ec9f5baa0796d475fc803514f4a5749d51/packages/shared/src/helpers/index.ts#L466-L489

The scheduler in Kusama AH (and soon PAH) keyes its agenda via a nonlocal block provider, which means these tests will fail on KAH.

See other E2E tests for how to do this, e.g. scheduler tests for KAH.

**Comment by rockbmb** [comment]
Will close #456 .

File: packages/shared/src/system.ts (hunk 8 above)
Comment (karolk91) [reply packages/shared/src/system.ts]: Existing test are actually fine, because the scenarios I introduced are using Relay's scheduler pallet - and that is always a "local" block provider

Before AHM I think parachains didn't have their scheduler (maybe Collectives only?), with AHM we are introducing scheduler pallet to Asset Hubs - so I can possibly create one more scenario specifiacally for post AHM Asset Hub such that it could use its own scheduler to execute the runtime upgrade

**Review by rockbmb — APPROVED** [review]

File: packages/shared/src/system.ts (hunk 7 above)
Comment (rockbmb) [reply packages/shared/src/system.ts]: Indeed - I was unaware that was the issue, as otherwise I'd have pointed you to a few instances of this pattern in PEt.

File: packages/kusama/src/assetHubKusama.system.e2e.test.ts [hunk 9]
```diff
@@ -0,0 +1,10 @@
+import { assetHubKusama, kusama } from '@e2e-test/networks/chains'
+import { type RelayTestConfig, registerTestTree, systemE2ETestsViaRelay } from '@e2e-test/shared'
+
+const testConfig: RelayTestConfig = {
+  testSuiteName: 'Kusama AssetHub System',
+  addressEncoding: 0,
+  blockProvider: 'Local',
```
[the remark this answers is not in the document]
Comment (karolk91) [reply packages/kusama/src/assetHubKusama.system.e2e.test.ts]: I have added both scenarios:

- using scheduler on relay --> local block provider (from relay perspective)
- using scheduler on AH (post-AHM) --> NonLocal provider in that case

**Comment by karolk91** [comment]
@rockbmb , few tests for Kusama are failing due to a bug where Preimage pallet is still filtered out post migration and PET scenarios here are extensively using Preimage pallet along with Scheduler to inject stuff for execution

This is affecting current live Kusama Relay. It that has been fixed by https://github.com/polkadot-fellows/runtimes/pull/957 but we will need to wait for Kusama Relay update

File: packages/shared/src/system.ts (hunk 8 above)
Comment (karolk91) [reply packages/shared/src/system.ts]: `testConfig.blockProvider` and extra scenario introduced in https://github.com/open-web3-stack/polkadot-ecosystem-tests/pull/411/commits/eee23572af1b3c67bf95a18b98f0b4b0d1ad44ab

File: packages/shared/src/system.ts (hunk 7 above)
Comment (karolk91) [reply packages/shared/src/system.ts]: done in https://github.com/open-web3-stack/polkadot-ecosystem-tests/pull/411/commits/eee23572af1b3c67bf95a18b98f0b4b0d1ad44ab

**Comment by karolk91** [comment]
- I have commented out failing scenarios for Kusama with TODO to enable them after Kusama 2.0 release (due to preimage pallet bug)
- added new scenarios for Kusama where Kusama Asset Hub is used as the "scheduler / governance" chain for other parachains and relay (so basically its like saying lets use KAH gov to upgrade other chains)
- added commented out post-AHM scenarios for Polkadot - once we merge this to master, I can prepare a PR to target polkadot-ahm branch and we should enable these tests there

File: packages/kusama/src/kusama.system.e2e.test.ts [hunk 10]
```diff
@@ -1,10 +1,20 @@
...
+// TODO: Uncomment after Kusama 2.0+ release due to polkadot-fellows/runtimes#957
+// const testConfig: RelayTestConfig = {
+//   testSuiteName: 'Kusama System',
+//   addressEncoding: 2,
+//   blockProvider: 'Local',
+// }
+
+// registerTestTree(systemE2ETests(kusama, testConfig))
+
+const testConfigForAssetHub: ParaTestConfig = {
```
Comment (rockbmb) [inline packages/kusama/src/kusama.system.e2e.test.ts]: This was fine as it was, `RelayTestConfig`

File: packages/polkadot/src/polkadot.system.e2e.test.ts [hunk 11]
```diff
@@ -8,3 +8,14 @@ const testConfig: RelayTestConfig = {
 }
 
 registerTestTree(systemE2ETests(polkadot, testConfig))
+
+// TODO: Uncomment Post-AHM on Polkadot
+
+// const testConfigForAssetHub: ParaTestConfig = {
```
Comment (rockbmb) [inline packages/polkadot/src/polkadot.system.e2e.test.ts]: This also needs to changed: `RelayTestConfig`.

I know it's commented out, but still.
